[package]
name = "cxx-experiment"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
cxx = "0.1.0"
cc = "1.0.50"
cmake = "0.1.42"

[dependencies]

